[project]
description = "API to get redeem codes from Hoyoverse games"
name = "hoyo-codes"
requires-python = ">=3.12"

[tool.poetry]
authors = ["seria <seria.ati@gmail.com>"]
description = "API to get redeem codes from Hoyoverse games"
license = "GPL-3.0"
name = "hoyo-codes"
package-mode = false
readme = "README.md"
version = "1.0.0"

[tool.poetry.dependencies]
aiohttp = "^3.9.3"
beautifulsoup4 = "^4.12.3"
fake-useragent = "^1.5.1"
fastapi = "^0.111.0"
lxml = "^5.2.1"
python = "^3.12"
uvicorn = "^0.30.0"
prisma = "^0.13.1"
genshin = "^1.7.0"
python-dotenv = "^1.0.1"
loguru = "^0.7.2"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.7.0"
ruff = "^0.5.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]