name: Ruff lint

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  ruff-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      
      - name: Set git user
        if: github.event_name == 'push'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run linter with fix
        if: github.event_name == 'push'
        run: ruff check --fix --output-format=github .
      
      - name: Run linter without fix
        if: github.event_name == 'pull_request'
        run: ruff check --output-format=github .

      - name: Commit auto-fix changes
        if: github.event_name == 'push'
        run: |
          git add .
          git diff-index --quiet HEAD || git commit -m "fix: Apply ruff auto-fixes"
      
      - name: Push changes
        if: github.event_name == 'push'
        run: git push origin main