name: Ruff format

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  ruff-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      
      - name: Set git user
        if: github.event_name == 'push'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      
      - name: Run formatter
        if: github.event_name == 'push'
        run: ruff format .

      - name: Commit formatting changes
        if: github.event_name == 'push'
        run: |
          git add .
          git diff-index --quiet HEAD || git commit -m "style: Apply ruff formatting"
      
      - name: Push changes
        if: github.event_name == 'push'
        run: git push origin main