name: Ruff lint

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - pyproject.toml
      - uv.lock
      - .github/workflows/ruff-lint.yml
  pull_request:
    branches:
      - main
    paths:
      - '**.py'
      - pyproject.toml
      - uv.lock
      - .github/workflows/ruff-lint.yml

jobs:
  ruff-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Run ruff lint
        uses: astral-sh/ruff-action@v3
